# Workflow to build new images after a push to main

name: build_images

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Update README
        run: |-
          python main.py
          # rename image files
          mv data/graphs/graph_1.png data/graphs/image_1.png
          mv data/graphs/graph_2.png data/graphs/image_2.png
          python update_readme_timestamp.py
      - name: Commit and push if changed
        run: |-
          git diff
          git config --global user.email "actions@users.noreply.github.com"
          git config --global user.name "GITHUB-bot"
          git add -A
          git commit -m "Updated content" || exit 0
          git push
